; THE ANCIENT SEAL — ORIGINAL GENESIS CHARACTER CONCEPT TILES
; Generated by tools/ancient_seal/generate-character-tiles.cjs.
; Uncompressed 4bpp; 24x24 pixels = 9 tiles x 32 bytes per frame.
; 3x3 sprite tiles are column-major; 16-color CRAM palettes.
; NOT INCLUDED IN ROM YET. SF2 map-sprite format/integration pending.

AncientSeal_Hero_Palette:
                dc.w $0000,$0422,$06AE,$046A,$0224,$0248,$06A6,$0AC2
                dc.w $0862,$026A,$0644,$0ECA,$0E82,$0222,$04AC,$0CEE

AncientSeal_Hero_Tiles:
                ; tile 0 (column 0, row 0)
                dc.l $00000000
                dc.l $00000004
                dc.l $00000004
                dc.l $00000004
                dc.l $00000004
                dc.l $00000004
                dc.l $00000004
                dc.l $00000000
                ; tile 1 (column 0, row 1)
                dc.l $00000000
                dc.l $00000111
                dc.l $00000177
                dc.l $00000177
                dc.l $00000333
                dc.l $00000333
                dc.l $00000333
                dc.l $00000322
                ; tile 2 (column 0, row 2)
                dc.l $00000322
                dc.l $00000177
                dc.l $00000088
                dc.l $00000001
                dc.l $00000001
                dc.l $00000044
                dc.l $00000044
                dc.l $00000000
                ; tile 3 (column 1, row 0)
                dc.l $00000000
                dc.l $44000004
                dc.l $44555444
                dc.l $44555444
                dc.l $44444444
                dc.l $44444444
                dc.l $44222224
                dc.l $12D222D2
                ; tile 4 (column 1, row 1)
                dc.l $12222222
                dc.l $12233322
                dc.l $76333337
                dc.l $7C333337
                dc.l $7C667777
                dc.l $76667777
                dc.l $76667777
                dc.l $7999EE99
                ; tile 5 (column 1, row 2)
                dc.l $7999EE99
                dc.l $78811111
                dc.l $888001AA
                dc.l $AA1001AA
                dc.l $AA1001AA
                dc.l $44400444
                dc.l $44400444
                dc.l $00000000
                ; tile 6 (column 2, row 0)
                dc.l $00000000
                dc.l $44000000
                dc.l $44000000
                dc.l $44000000
                dc.l $44000000
                dc.l $44000000
                dc.l $44000000
                dc.l $10000000
                ; tile 7 (column 2, row 1)
                dc.l $10000000
                dc.l $11100000
                dc.l $61101000
                dc.l $C11EEE00
                dc.l $C333B000
                dc.l $6333B000
                dc.l $6333B000
                dc.l $9322B000
                ; tile 8 (column 2, row 2)
                dc.l $9322B000
                dc.l $1110B000
                dc.l $10001000
                dc.l $10001000
                dc.l $10000000
                dc.l $44000000
                dc.l $44000000
                dc.l $00000000

AncientSeal_Elder_Palette:
                dc.w $0000,$0222,$0CEE,$08AA,$0246,$026A,$0484,$04A6
                dc.w $0462,$028E,$04CE,$0468,$0EC6,$06CA,$0264,$08EE

AncientSeal_Elder_Tiles:
                ; tile 0 (column 0, row 0)
                dc.l $00005550
                dc.l $00005554
                dc.l $00000454
                dc.l $00000054
                dc.l $00000004
                dc.l $00000004
                dc.l $00000004
                dc.l $00000004
                ; tile 1 (column 0, row 1)
                dc.l $00000004
                dc.l $00000000
                dc.l $00000000
                dc.l $00000111
                dc.l $00007777
                dc.l $00007777
                dc.l $00007777
                dc.l $00007777
                ; tile 2 (column 0, row 2)
                dc.l $00007333
                dc.l $00007333
                dc.l $00000188
                dc.l $00000188
                dc.l $00000188
                dc.l $00000114
                dc.l $00000004
                dc.l $00000000
                ; tile 3 (column 1, row 0)
                dc.l $00000000
                dc.l $00000000
                dc.l $40000000
                dc.l $40000000
                dc.l $11111111
                dc.l $12222222
                dc.l $12222222
                dc.l $12222222
                ; tile 4 (column 1, row 1)
                dc.l $12C222C2
                dc.l $12222222
                dc.l $13333333
                dc.l $13333333
                dc.l $13222223
                dc.l $11222221
                dc.l $86222227
                dc.l $86777777
                ; tile 5 (column 1, row 2)
                dc.l $86777777
                dc.l $86777777
                dc.l $EEE77777
                dc.l $EEE77777
                dc.l $EEE77766
                dc.l $44411444
                dc.l $44400444
                dc.l $00000000
                ; tile 6 (column 2, row 0)
                dc.l $00555000
                dc.l $04555000
                dc.l $44544000
                dc.l $44500000
                dc.l $14000000
                dc.l $14011110
                dc.l $14019990
                dc.l $1401AF90
                ; tile 7 (column 2, row 1)
                dc.l $1401AA90
                dc.l $10019990
                dc.l $1001BBB0
                dc.l $11100B00
                dc.l $17770B00
                dc.l $17770B00
                dc.l $77770B00
                dc.l $77330B00
                ; tile 8 (column 2, row 2)
                dc.l $77330B00
                dc.l $77100B00
                dc.l $77100B00
                dc.l $77100B00
                dc.l $66100B00
                dc.l $41100B00
                dc.l $40000B00
                dc.l $00000000
